In [1]:
import tensorflow as tf  

#两个矩阵的对应元素各自相乘！！
x=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
y=tf.constant([[0,0,1.0],[0,0,1.0],[0,0,1.0]])
#注意这里这里x,y要有相同的数据类型，不然就会因为数据类型不匹配而出错
z=tf.multiply(x,y)

#两个数相乘
x1=tf.constant(1)
y1=tf.constant(2)
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z1=tf.multiply(x1,y1)

#两个数相乘
x1=tf.constant([1,2,3])
y1=tf.constant([2,2,2])
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z0=tf.multiply(x1,y1)

#数和矩阵相乘
x2=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])
y2=tf.constant(2.0)
#注意这里这里x1,y1要有相同的数据类型，不然就会因为数据类型不匹配而出错
z2=tf.multiply(x2,y2)

#两个矩阵相乘
x3=tf.constant([[1.0,2.0,3.0],[1.0,2.0,3.0],[1.0,2.0,3.0]])  
y3=tf.constant([[0,0,1.0],[0,0,1.0],[0,0,1.0]])
#注意这里这里x,y要满足矩阵相乘的格式要求。
z3=tf.matmul(x,y)

with tf.Session() as sess:  
    print(sess.run(z))
    print(sess.run(z1))
    print(sess.run(z0))
    print(sess.run(z2))
    print(sess.run(z3))

[[0. 0. 3.]
 [0. 0. 3.]
 [0. 0. 3.]]
2
[2 4 6]
[[2. 4. 6.]
 [2. 4. 6.]
 [2. 4. 6.]]
[[0. 0. 6.]
 [0. 0. 6.]
 [0. 0. 6.]]


In [9]:
import tensorflow as tf
 
x = [[1,2,3],
     [1,2,3]]
 
xx = tf.cast(x, tf.float32)

sig = tf.sigmoid(xx)

xxs = tf.reduce_sum(xx, axis=1)
 
sum_all = tf.reduce_sum(xx, keepdims=False)
sum_0 = tf.reduce_sum(xx, axis=0, keepdims=False)
sum_1 = tf.reduce_sum(xx, axis=1, keepdims=False)
sum_2 = tf.reduce_sum(xx, axis=1, keepdims=True)
 
#如果axis为None，input_tensor的维度降为1
#如果axis为0，矩阵按行计算，维度降低一个维度
#如果axis为1，矩阵按列计算，维度降低一个维度
#如果keep_dims==true，保持维度不变，矩阵按行或者按列计算

with tf.Session() as sess:
    xxp, sigp, s_a,s_0,s_1,s_2, xxx = sess.run([xx, sig, xxs, sum_all, sum_0, sum_1, sum_2])
 
print(xxp)
print("+++++++++++++++++++")
print(sigp)
print("+++++++++++++++++++")
print(s_a)
print(s_0)
print(s_1)
print(s_2)
print(xxx)


[[1. 2. 3.]
 [1. 2. 3.]]
+++++++++++++++++++
[[0.7310586  0.880797   0.95257413]
 [0.7310586  0.880797   0.95257413]]
+++++++++++++++++++
[6. 6.]
12.0
[2. 4. 6.]
[6. 6.]
[[6.]
 [6.]]


In [1]:
import tensorflow as tf
count = 0
global_val = ""
with open("/data0/guolei7/data/data_train.txt") as f:
    for line in f:
        count += 1
        if count == 5:
            break
        cols = tf.decode_csv(line, ['', '', '0', '', '0', '0', '200', '',''], field_delim='\t')
        global_val = cols[5]
        print(cols[5])
    print("ok")
        
with tf.Session() as sess:
    print(sess.run(global_val))

IOError: [Errno 2] No such file or directory: '/data0/guolei7/data/data_train.txt'