In [62]:
#只适用于值为整数的类别型变量，实际输出如下：

import tensorflow as tf
sess=tf.Session()

#特征数据
#features = {'birthplace': [[1],[1],[3],[4]]}
features = {'birthplace': [-2, -1, 1, 2, 3, 4, 100]}

#特征列
birthplace = tf.feature_column.categorical_column_with_identity("birthplace", num_buckets=10, default_value=0)
birthplace = tf.feature_column.indicator_column(birthplace)
#组合特征列
columns = [
    birthplace
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)
v=sess.run(inputs)
print(v)
#输出为birthplace的one-hot结果，num_buckets用于确定每一个one-hot向量的最大特征类别数

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [7]:
#主要用于处理非整数型的类别特征，两个函数的区别在于处理变量类别的多少，
#数量前者对应类别少的情况，所有可能的类别可以直接输入，后者对应类别多的情况，所有可能的类别可以存在一个文件中输入
import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    'sex': ['male', 'male', 'female', 'female'],
}

#特征列
sex_column = tf.feature_column.categorical_column_with_vocabulary_list('sex', ['male', 'female'])
sex_column = tf.feature_column.indicator_column(sex_column)
#组合特征列
columns = [
    sex_column
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
print(v)

[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]


In [49]:
#对于处理包含大量文字或数字类别的特征时可使用hash的方式，这能快速地建立对应的对照表，缺点则是会有哈希冲突的问题。
#hash_bucket_size的大小一般设置为总类别数的2-5倍，该函数适用于不能确定所有类别样式的类别变量

import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    'department': ['sport', 'sport', 'gardening', 'drawing', 'travelling'],
}

#特征列
department = tf.feature_column.categorical_column_with_hash_bucket('department', 10, dtype=tf.string)
department = tf.feature_column.indicator_column(department)
#组合特征列
columns = [
    department
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
print(v)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [58]:
#对于处理包含大量文字或数字类别的特征时可使用hash的方式，这能快速地建立对应的对照表，缺点则是会有哈希冲突的问题。
#hash_bucket_size的大小一般设置为总类别数的2-5倍，该函数适用于不能确定所有类别样式的类别变量

import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    '9': ['sport', 'sport', 'gardening', 'drawing', 'travelling'],
    '10': ['gg', 'ss', 'gg', 'dd', 'tt'],
}

features1 = {
    '0': ['sport', 'sport', 'gardening', 'drawing', 'travelling'],
    '1': ['gg', 'ss', 'gg', 'dd', 'tt'],
}


#特征列
department = tf.feature_column.categorical_column_with_hash_bucket('9', 10, dtype=tf.string)
department = tf.feature_column.indicator_column(department)

#特征列
dd = tf.feature_column.categorical_column_with_hash_bucket('10', 10, dtype=tf.string)
dd = tf.feature_column.indicator_column(dd)

#组合特征列
columns = [
    dd,
    department
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)
#inputs = tf.feature_column.input_layer(features1, columns)
#features 和features1的查询结果不一样，是根据featrure的key按照字母序排序后查询结果的，跟组合特征列columns的顺序没有关系

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
print(v)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [60]:
#numeric_column：该函数主要用于处理连续型变量，
#即可以是float类型也可以是int类似，从table中读取对应的(key)column，并把它转成dtype的格式

import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    'sale': [1.2, 2.3, 1.2, 1.5, 2.2]
}

#特征列
sale = tf.feature_column.numeric_column("sale", default_value=0.0)
#组合特征列
columns = [
    sale
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
print(v)

[[1.2]
 [2.3]
 [1.2]
 [1.5]
 [2.2]]


In [61]:
#bucketized_column: 该函数将连续变量进行分桶离散化，输出one-hot的结果，方便连续值指标与分类变量进行交叉特征构建

import numpy as np
import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    'sale': [-0.1, 0.1, 0.2, 0.5, 1.0, 0.2]
}

#特征列
step_val = 1.0 / 2
boundaries = list(np.arange(0, 1, step_val))
print(boundaries)
print("+++++++++++++++++++")
sale = tf.feature_column.bucketized_column(
    tf.feature_column.numeric_column('sale', default_value=0.0), boundaries=boundaries)
#组合特征列
columns = [
    sale
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
print(v)

[0.0, 0.5]
+++++++++++++++++++
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]


In [59]:
#crossed_column：特征交叉，在有些情况下，特征独自编码与多维特征交叉后的特征特性会有不一样的结果。
#该函数不能对hash映射之后的特征进行交叉
import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    'sex': [1, 2, 1, 1, 2],
    'department': ['sport', 'sport', 'drawing', 'gardening', 'travelling'],
}

#特征列
department = tf.feature_column.categorical_column_with_vocabulary_list('department', ['sport','drawing','gardening','travelling'], dtype=tf.string)
sex = tf.feature_column.categorical_column_with_identity('sex', num_buckets=2, default_value=0)
sex_department = tf.feature_column.crossed_column([department, sex], 16)
sex_department = tf.feature_column.indicator_column(sex_department)
#组合特征列
columns = [
    sex_department
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
print(v)

[[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
#embedding_column：把categorical的data，借由lookup table的方式找寻对应的feature vector来表示。
#假设有81个单词，若使用categorical_column_vocbulary_list，然后转成numerical的indicator_column，
#则需要81维度来描述此些单词，这样极易造成数据的稀疏化，对于推荐系统而言，大维度的稀疏数据对于结果的影响较大，
#因此我们考虑使用embedding_column，来对数据进行压缩

import tensorflow as tf
sess=tf.Session()

#特征数据
features = {
    'sex': [0, 1, 0, 0, 1],
    'department': ['sport', 'sport', 'drawing', 'gardening', 'travelling'],
}

#特征列
department = tf.feature_column.categorical_column_with_vocabulary_list('department', ['sport','drawing','gardening','travelling'], dtype=tf.string)
sex = tf.feature_column.categorical_column_with_identity('sex', num_buckets=2, default_value=0)

sex_department = tf.feature_column.crossed_column([department, sex], 16)
sex_department_emb = tf.feature_column.embedding_column(sex_department, 5, combiner='sqrtn')

#组合特征列
columns = [
    sex_department_emb
]

#输入层（数据，特征列）
inputs = tf.feature_column.input_layer(features, columns)

#初始化并运行
init = tf.global_variables_initializer()
sess.run(tf.tables_initializer())
sess.run(init)

v=sess.run(inputs)
#输出为交叉特征的embading向量，embedding_column的输入为处理之后的特征变量，可以是categorical也可以是dense的
print(v)

[[ 0.6841228  -0.6059169   0.0112622  -0.05250439  0.79430753]
 [-0.10248739 -0.00268992 -0.81676567 -0.40964803 -0.24823937]
 [-0.16232549 -0.26419324 -0.22975169 -0.8299208  -0.26175195]
 [-0.4624797  -0.06243371  0.12362447  0.6441867  -0.13424385]
 [-0.09251136 -0.29220805  0.70454067 -0.14150065 -0.06217364]]
